advisor: 'localhost:6000'
hostdb:
  'mockserver:80': mock
  'mockserver:8080': mock
  'localhost:8080': mock
  '192.168.1.64:8080': mock  
targetdb:
  mock: 'http://localhost:3000'
serverconfig:
  mock:
    opentime: 2018-09-22 19:00:00
    bording: 60 #minute 
    maxusers: 2